### ISSUE TITLE
Roadmap To The Version 1.0.0

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#93]
I think it’s time to consider bumping Vuex ORM version to 1.0.0. The biggest reason is that luckily, I hear many people using Vuex ORM to build their application, and there are already few plugins out there. Hence we should fix the API and make whole application more stable.

But another reason is that Vuex ORM has almost all relationship types supported. We do have other feature requests as well, but I think some of them can be implemented after version 1.0.0.

Here are things I would like to do before bumping to 1.0.0.

- [x] Add [Has Many Through](https://laravel.com/docs/5.6/eloquent-relationships#has-many-through) relationship.
- [x] #60 Add action methods to the Model class.
- [x] #83 Add more complete lifecycle hooks.
- [x] #90 Add feature to update primary key value with its related records.
- [x] #98 Remove lodash from dependency.
- [x] #104 Make nested relation loading work with same top level relation name.
- [x] #110 Add specific type attributes such as `string` or `number`.
- [x] #136 Define lifecycle hook at models.
- [x] #143 Implement action to create a fresh record with default values.
- [x] #150 Add save method to the model.
- [x] #152 Deep relationship loading fails with morph relation.
- [x] #164 0.25.1 forEach of null bug.
- [x] #168 Auto increment the ID value when the value is null.
- [x] #171 Add `nullable` chain to the attribute definitions.
- [x] #231 Save class instances directly to the store.
- [ ] Fix all issues labeled as `bug`.
- [x] Refactor the documentation.

I would really love to hear any ideas or request regarding this plan from the community. I didn’t think Vuex ORM would become like it’s today that many people use in their project. I get contacted almost every day about this library.

I’m so thrilled, and I’m willing to make Vuex ORM even more powerful toward the future. Thank you all!

**Comment by iNaD** [comment]
Thank you for the awesome work already done. Coming from Ember.js and other frameworks already having an ORM etc. I was pretty lost at first using Vue for SPAs.

As we already talked on Twitter, I think removing Lodash as a dependency would be great. It is a very good library, but at the same time it's another dependency which is pulled in and most of the functionality is natively available in js these days.

**Comment by phortx** [comment]
Yey, I thank you too for your awesome work on this wonderful peace of software :)

The plan looks good and I think the roadmap is very reasonable in my opinion.

**Comment by timoschwarzer** [comment]
I can just say what the others already said. Thank you for your hard work and for your instant and nice support everytime @kiaking! This library is awesome! :100:

**Comment by kiaking** [comment]
Thank you all for the such a kind word! You guys are seriously making me cry 😭 

@iNaD Yeah lets add one in here. I'll make issue for that and link to the list.

**Comment by razvanioan** [comment]
Hi again @kiaking 

Two more items that maybe I'm missing :)

* **v-model sync**
I see that now v-model can be used to read record data but it would have been nice to be able to update it as well (without the need of an update event)
* **model validations**
Maybe this can already be implemented as I've just understood that models are classes that we can add custom methods to

**Comment by kiaking** [comment]
Hi @razvanioan, thanks for the feedback!

> model validations

Yea you can add any validation method to the class if you want. I don't know if having validation feature in the model or Vuex ORM is a nice idea or not. Because when using Vue, most of the time I think validation is done at Vue Component level. Using something like Vuelidate.

Do you have any proposal API for defining validations? Maybe it worth discussing. If it's interesting enough, we could create a new issue to talk about this deeply!

> v-model

Yes, your correct, this is more of a Vue and Vuex spec, but if you want use v-model, you have to create `set` and `get` in a computed property.

**Comment by longuid** [comment]
hello @kiaking , 
i think Model can add some simple function, like remove, update, 
its will make code simple.

(i will read all the code, hopefully i can help in the feature,  O(∩_∩)O  )

**Comment by kiaking** [comment]
@longuid Thanks for the comment! Actually I think that is #60 ? We're planning to add model method like `user.create` or `user.update()` which does pretty much same as `store.dispatch('entities/users/create')` or `store.dispatch('entities/users/update')`.

**Comment by kiaking** [comment]
Added #104 to the list. I saw many people having trouble with this one 🔥

**Comment by kiaking** [comment]
Now Has Many Through relation is out! https://github.com/vuex-orm/vuex-orm/releases/tag/v0.21.0

**Comment by razvanioan** [comment]
Regarding validation on the model itself.

I have a lot of experience with the ExtJS framework, which has `validators` defined on the [model](http://docs.sencha.com/extjs/6.5.3/modern/Ext.data.Model.html#cfg-validators), and this is making sense.

Think that you might use a particular model in multiple components / views.

Why should you (re)write simple validations connected to the model(s) in each of them ?

For example some min / max values, or pattern for specific field types, or even better conditions between models' fields (if field A is having this value, field B can have only these values, and so on)

That's a thought ;)

**Comment by kiaking** [comment]
@razvanioan Yea that makes sense. It could be good idea to have this kind of feature. I want to discuss how the public API should look like. I've opened #108 for this so let's continue the discussion there ❤️

**Comment by JonasKraska** [comment]
looking forward to use lifecycle hooks in models ...

**Comment by kiaking** [comment]
@JonasKraska This is now possible with Vuex ORM 0.29.0! 🎉  However, I needed to introduce breaking change where you can no longer define lifecycle hook at actions... Please see the release note for more detail!
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.29.0

**Comment by kiaking** [comment]
Now every issue we planned to resolve before version 1.0.0 has completed! 🎉 

Now I'll look through current issues to see if there's any bugs that we should fix before releasing v1.0.0, and I would like to refactor the whole doc at this point. Then, make the long awaited release.

We're almost there! 🚀

**Comment by RomainLanz** [comment]
Hey 👋 

Looking at the issue #171 it seems that you want by using the `nullable()` approach. I really believe having a `notNullable()` would be better. This is what we are using in Adonis for our migration. The main reason we do so is because there's higher chance that the field is null by default than it's not.

Nevertheless, this isn't so important 😝 

I'm currently using TypeScript with your library, and I don't know if it's because of wrong typing but I need to provide a default value for any attributes, even if they are nullable. I believe the default attribute should be `null` so we can avoid having the following:

![Screenshot 2019-03-19 at 11 10 52](https://user-images.githubusercontent.com/2793951/54597998-e197f600-4a37-11e9-9233-466f66e8e70c.png)

**Comment by kiaking** [comment]
Ahh Interesting. Maybe it is. Or at least, if we set `nullable`, make the default value as `null`.

```js
name: this.string().nullable()
```

**Comment by AdrienPoupa** [comment]
Hello there! Any updates on the 1.0.0 release? :)

**Comment by kiaking** [comment]
@AdrienPoupa Hi! Thank you for the comment. Yeah it is in progress. I'm now trying to fix all the existing bugs, and refactor the documentation!

**Comment by kiaking** [comment]
We're almost here... Just need to fix all of the issue labeled as `bug` and do some serious documentation refactoring! (in progress!)

**Comment by kiaking** [comment]
Document refactoring is done! It’s not perfect yet, but I believe it got much better. So, the rest is to fix all the bugs!

**Comment by kiaking** [comment]
There's still lots to go with bug fixes. I've created GitHub milestone instead so let's track the progress here!
https://github.com/vuex-orm/vuex-orm/milestone/1
